import { MarginBox } from "../components/margin-box.slint";
import { HorizontalBox } from "std-widgets.slint";
import { Frame } from "../components/frame.slint";
import { Palette } from "../palette.slint";
import { Lyrics, LyricsPropery } from "../components/lyrics.slint";

export global LyricsPageProperty {
    in-out property <image> background;
    in-out property <image> cover;
    in-out property <bool> display;

    in-out property <int> id_1;
    in-out property <int> id_2;
    callback show();
}

export component LyricsPage inherits Rectangle{
    visible: lazy_hide.output;
    
    clip: true;

    lazy_hide := Timer {
        out property <bool> output;
        
        property <bool> input : LyricsPageProperty.display;
        changed input => {
            if input == true {
                output = true;
            }
        }

        running: !input;
        interval: 150ms;
        triggered => {
            output = input;
        }
    }

    Image {
        z: 10;
        width: 100%;
        height: 100%;
        image-fit: cover;
        source: LyricsPageProperty.background;
    }

    title_bar := Frame {
        z: 30;
        x: 0;
        y: 0;
        width: 100%;
        enable: self.visible;
    }

    opacity: LyricsPageProperty.display ? 1 : 0;

    animate opacity {
        duration: 150ms;
        easing: ease-out;
    }

    MarginBox {
        z: 20;
        height: 100%;
        width: 100%;
        margin-top : title_bar.height;
        background: Palette.white.with-alpha(0.6);
        HorizontalBox {
            VerticalLayout {
                height: 100%;
                alignment: end;
                width: 300px;

                cover_ele := MarginBox {
                    width: parent.width;
                    height: parent.width;

                    margin: 20px;
                    Rectangle {
                        // transform-scale: !LyricsPageProperty.display ? 0.4 : 1;
                        // transform-origin: { x: self.width / 2, y: self.height };
                        width: 100%;
                        height: 100%;
                        clip: true;
                        border-radius: 8px;
                        drop-shadow-blur: 8px;
                        drop-shadow-color: Palette.neutral-tertiary;
                        Image {
                            width: 100%;
                            height: 100%;
                            image-fit: cover;
                            source: LyricsPageProperty.cover;
                        }

                        // animate transform-scale {
                        //     duration: 125ms;
                        //     easing: ease-in; 
                        // }
                    }
                }
            }

            lyrics_view := Lyrics {
                horizontal-stretch: 1;
                height: 100%;
                visible: root.visible;
            }
        }
    }
}
