import { ListView, HorizontalBox, TabWidget, ScrollView, Button } from "std-widgets.slint";
import { Palette } from "../palette.slint";
import { SongDetail, Songlist } from "../components/songlist.slint";
import { HorizontalDivider } from "../components/divider.slint";
import { MarginBox } from "../components/margin-box.slint";
import { AppStatus } from "../app-status.slint";

import "../assets/fonts/HarmonyOS_Sans_SC_Regular.ttf";

export global PlaylistProperty {
    in-out property <[SongDetail]> song-data;
    callback load-data(id_1: int, id_2: int);
    in-out property <string> name;
    in-out property <image>  cover;
    in-out property <string> create-time;
    in-out property <string> description;
    in-out property <int> play-count;
    in-out property <bool> subscribed;
    in-out property <int> track-count;
    in-out property <string> creator-name;
    in-out property <image> creator-avatar;
    in-out property <bool> subscribable;
}


export component HeaderInner inherits MarginBox{
    in property <bool> minimize;

    border-radius: 10px;
    background: Palette.white;
    border-width: 1px;
    border-color: Palette.neutral-light;

    margin: 15px;

    // MarginBox {
        HorizontalLayout {
            height: 100%;
            width: 100%;
            Rectangle {
                Image {
                    source: PlaylistProperty.cover;
                    height: parent.height;
                    width: parent.width;
                }
                border-radius: 8px;
                clip: true;
                width: self.height;
            }

            MarginBox {
                margin-left: 25px;
                horizontal-stretch: 1;
                height: 100%;
                VerticalLayout {
                    height: 100%;
                    padding: 0px;
                    
                    property <length> split-height: 4px;
                    // property <length> content-height: parent.height;
                    property <length> title-height: 30px;
                    property <length> creator-height: 30px;
                    property <length> control-height: 30px;
                    property <length> description-height:parent.height - title-height - creator-height - control-height - split-height * 3;
                    
                    spacing: split-height;

                    Text {
                        text: PlaylistProperty.name;
                        font-size: 20px;
                        font-weight: 600;
                        height: title-height;
                        overflow: elide;
                    }

                    HorizontalLayout {
                        height: creator-height;
                        spacing: 0px;
                        alignment: start; 
                        Rectangle {
                            Image {
                                source: PlaylistProperty.creator-avatar;
                                height: parent.height;
                                width: parent.width;
                            }
                            border-radius: creator-height / 2;
                            width: self.height;
                            clip: true;
                        }

                        Rectangle {
                            width: 4px;
                        }

                        Text {
                            text: PlaylistProperty.creator-name;
                            font-size: 12px;
                            vertical-alignment: center;
                            color: Palette.neutral-secondary;
                        }

                        Rectangle {
                            width: 10px;
                        }

                        Text {
                            text: PlaylistProperty.create-time + "创建";
                            font-size: 12px;
                            vertical-alignment: center;
                            color: Palette.neutral-tertiary;
                        }
                    }


                    Rectangle {
                        clip: true;
                        height: description-height;
                        // vertical-stretch: 1;
                        Text {
                            text: PlaylistProperty.description;
                            wrap: word-wrap;
                            overflow: elide;
                            font-size: 12px;
                            width: 100%;
                            height: parent.height;
                        }
                    }

                    HorizontalLayout {
                        height: control-height;
                        alignment: start;
                        spacing: 10px;
                        padding: 0px;
                        Button {
                            text: "播放全部";
                            
                            icon: @image-url("../assets/icon/svg/play.svg");
                            colorize-icon: true;
                            primary: true;
                        }

                        if PlaylistProperty.subscribable: Button {
                            text: PlaylistProperty.subscribed ? "取消收藏" : "收藏";
                            icon: PlaylistProperty.subscribed ? @image-url("../assets/icon/svg/collections_empty.svg") 
                                : @image-url("../assets/icon/svg/collections_empty.svg");
                            colorize-icon: true;
                        }
                    }
                }
            }
        }
    //}
}


export component Header inherits MarginBox {
    in property <length> margin-page;
    in property <bool> minimize;

    margin-horizontal: margin-page;
    margin-top: 10px;
    margin-buttom: 30px;
    vertical-stretch: 0;
    height: !minimize ? 240px : 180px;

    animate height {
         duration: 100ms;
    }

    HeaderInner {
        minimize: root.minimize;
    }
}

export component Playlist inherits Rectangle{
    in-out property <int> playlist-id-1: 4;
    in-out property <int> playlist-id-2: 427189786;

    in-out property <length> margin;

    // property <bool> view-content: songlist.view-content;

    VerticalLayout {
        Header {
            margin-page: root.margin;
            minimize: songlist.view-content;
        }

        songlist := Songlist {
            song-data: PlaylistProperty.song-data;
            margin: root.margin;
        }
    }

    init => {
        PlaylistProperty.load-data(playlist-id-1, playlist-id-2);
    }
}
