import { SongDetail } from "../types/types.slint";
import { Songlist } from "../components/songlist.slint";
import { ScrollView } from "std-widgets.slint";
// import { PlayerProperty } from "../components/player.slint";

export global PlayQueueProperty {
    in-out property <int> base-id-1;
    in-out property <int> base-id-2;
    in-out property <int> base-type;

    out property <int> base-type-playlist: 1;
    out property <int> base-type-album: 2;
    out property <int> base-type-artist: 3;
    out property <int> base-type-none: 0;

    in-out property <[SongDetail]> queue;

    callback reload-queue();
    callback remove-songs();
}

export component PlayQueue inherits Rectangle{
    in property <length> margin;
    Timer {
        running: true;
        interval: 80ms;
        triggered => {
            PlayQueueProperty.reload-queue();
        }
    }

    VerticalLayout {
        HorizontalLayout {
            alignment: start;
            padding-left: margin;
            padding-right: margin;
            Text {
                vertical-alignment: center;
                text: "播放队列";
                font-size: 40px;
            }
        }
        list := Songlist {
            song-data: PlayQueueProperty.queue;
            base-id-1: PlayQueueProperty.base-id-1;
            base-id-2: PlayQueueProperty.base-id-2;
            base-type: PlayQueueProperty.base-type;
            margin: root.margin;
            delete => {
                PlayQueueProperty.remove-songs();
            }
        }
    }

    ScrollView {
        height: list.height;
        width: list.width;
        x: list.x;
        y: list.y;
        viewport-height: list.content-viewport-height;
        scrolled => {
            list.set-viewport-y(self.viewport-y);
        }
    }
}

