import { AppStatus, PlayerStatus } from "../app-status.slint";
import { Slider } from "std-widgets.slint";
import { MarginBox } from "margin-box.slint";
import { HorizontalDivider } from "divider.slint";
import { Palette } from "../palette.slint";
import { IconFontFilled } from "../assets/icon/iconfont.slint";


component PauseButton inherits Rectangle {
    in property <color> common-background;
    Rectangle {
        states [
            hover when pause.has-hover :{
                background: @linear-gradient(
                    135deg,
                    #006EBE 0%,
                    #1C5DAF 25%,
                    #384E9E 50%,
                    #543E8E 75%,
                    #703080 100%
                );
                pause-container.background: Palette.neutral-lighter-alt;
            }
            common when !pause.has-hover :{
                background: @linear-gradient(
                    135deg,
                    #0078D4 0%,
                    #2068C2 25%,
                    #4058B0 50%,
                    #6048A0 75%,
                    #803890 100% 
                );
                pause-container.background: common-background.with-alpha(1);
            }
        ]

        width: 56px;
        border-radius: 28px;

        pause-container := Rectangle {
            border-radius: 24px;
            width: parent.width - 8px;
            height: parent.height - 8px;
            
            background: root.background;

            pause := TouchArea {
                IconFontFilled {
                    vertical-alignment: center;
                    text:  PlayerStatus.status-tragger == PlayerStatus.status-none 
                        || PlayerStatus.status-tragger == PlayerStatus.status-pause? "\u{f611}" : "\u{e8e0}";
                    font-size: 28px;
                }

                clicked => {
                    PlayerStatus.pause-resume();
                }
            }
        }
    }
}

component CommonButton inherits Rectangle{
    in property <string> iconfont;
    
    callback clicked();

    ta := TouchArea {
        clicked => { root.clicked() }
    }

    width: 30px;
    height: 30px;
    border-radius: 4px;
    IconFontFilled {
        text: iconfont;
        font-size: 20px;
    }

    states [
        hover when ta.has-hover : {
            background: Palette.neutral-lighter;
        }
    ]

}

export component Player inherits Rectangle {
    // test 
    background: white;

    Timer {
        interval: PlayerStatus.event-loop-gap;
        running: true;
        triggered => {
            PlayerStatus.event-loop();
            slider.update-slider();
        }
    }

    height: 111px;
    HorizontalDivider {
        y: 0px;
    }
    // MarginBox {
    //     margin-horizontal: 10px;
        VerticalLayout {
            y: 1px;
            height: 110px;
            HorizontalLayout {
                height: 30px;
                padding-left: 10px;
                padding-right: 10px;
                Text {
                    text: PlayerStatus.played-duration;
                    vertical-alignment: center;
                }

                MarginBox {
                    horizontal-stretch: 1;
                    margin-horizontal: 15px;

                    slider := Slider {
                        minimum: 0;
                        maximum: PlayerStatus.total-duration-int;
                        value: 0;
                        width: 100%;
                        step: 10 * 1000;
                        property <int> current-duration;
                        property <bool> user-inputing;

                        released(position) => {
                            PlayerStatus.seek-to-duration(position);
                            user-inputing = false;
                        }

                        changed(value) => {
                            user-inputing = true;
                        }
                        
                        
                        function update-slider() {
                            if !user-inputing {
                                self.value = PlayerStatus.played-duration-int;
                            }
                        }
                    }
                }
                
                Text {
                    text: PlayerStatus.total-duraiton;
                    vertical-alignment: center;
                }
            }
        
            MarginBox {
                margin-horizontal: 5px;
                margin-buttom: 5px;
                // 详情
                detail := Rectangle {
                    x: 0;
                    width: (parent.width - control.width) / 2;
                    ta_detail := TouchArea {
                        
                    }
                    // 图片
                    HorizontalLayout {
                        alignment: start;
                        spacing: 10px;

                        Rectangle {
                            height: 100%;
                            width:  self.height - 10px + 5px;
                            picture := Rectangle {
                                x: 5px;
                                border-width: 1px;
                                border-color: Palette.neutral-quaternary;
                                clip: true;
                                border-radius: 4px;
                                width: parent.width - 5px;
                                height: self.width;
                                Image {
                                    width: 100%;
                                    height: 100%;
                                    source: PlayerStatus.playing-song.image;
                                }
                            }
                        }


                        VerticalLayout {
                            spacing: 4px;
                            // 歌曲名
                            Text {
                                vertical-alignment: center;
                                text: PlayerStatus.playing-song.name;
                                color: Palette.neutral-primary;
                                font-size: 22px;
                                font-weight: 500;
                                overflow: elide;
                            }
                            // 歌手
                            if !PlayerStatus.playing-song.singer.is-empty : Text {
                                vertical-alignment: top;
                                text:  "\u{2022} " + PlayerStatus.playing-song.singer;
                                color: Palette.neutral-secondary;
                                overflow: elide;
                                font-size: 14px;    
                            }
                        }
                    }
                    horizontal-stretch: 1;
                    border-radius: 6px;
                    states [
                        hover when ta_detail.has-hover :{
                            background: Palette.neutral-light;
                        }
                    ]
                }

                control := Rectangle {
                    x: detail.width;
                    width: 240px;

                    Rectangle {
                        height: 56px;
                        HorizontalLayout {
                        spacing: 10px;
                        
                        Rectangle {
                            horizontal-stretch: 1;
                            CommonButton {
                                iconfont: "\u{f172}";
                            }
                            // no repeat f175
                        }

                        Rectangle {
                            horizontal-stretch: 1;
                            CommonButton {
                                iconfont: "\u{e9d2}";
                                clicked => {
                                    PlayerStatus.prev();
                                }
                            }
                        }

                        Rectangle {
                            horizontal-stretch: 2;
                            PauseButton {
                                common-background: root.background;
                            }
                        }
                        
                        Rectangle {
                            horizontal-stretch: 1;
                            CommonButton {
                                iconfont: "\u{e876}";
                                clicked => {
                                    PlayerStatus.next();
                                }
                            }
                        }

                        Rectangle {
                            horizontal-stretch: 1;
                            CommonButton {
                                iconfont: "\u{ef39}";
                            }
                            // no shuffle ef3f
                        }
                    }
                    }

                }

                more := Rectangle {
                    width: (parent.width - control.width) / 2;
                    x: parent.width - self.width;
                    horizontal-stretch: 1;
                }
            }
        }
    // }
}
