// playlist/82430854

import { LineEdit } from "std-widgets.slint";
import { IconFont } from "../assets/icon/iconfont.slint";
export component T {
    ta_main := TouchArea {
        property <bool> left-down: false;
        property <KeyboardModifiers> modifiers;
        double-clicked => {
        }

        clicked => {
        }

        pointer-event(event) => {
            if event.button == PointerEventButton.left {
                if event.kind == PointerEventKind.down {
                    left-down = true;
                } else {
                    left-down = false;
                }

                debug(left-down);

                if event.kind == PointerEventKind.down || event.kind == PointerEventKind.up {
                    modifiers = event.modifiers;
                }
            }
        }
    }
    IconFont {
        text: "\u{e856}";
    }
}

export component ContextMenu {
    ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("Cut");
                activated => { debug("Cut"); }
            }
            MenuItem {
                title: @tr("Copy");
                activated => { debug("Copy"); }
            }
            MenuItem {
                title: @tr("Paste");
                activated => { debug("Paste"); }
            }
            MenuSeparator {}
            Menu {
                title: @tr("Find");
                MenuItem {
                    title: @tr("Find Next");
                }
                MenuItem {
                    title: @tr("Find Previous");
                }
            }
        }
    }
}
