import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import { SideBar, SideBarProperty, SideBarItemMessage } from "sidebar.slint";
import { Palette } from "palette.slint";
import { Login, LoginProperty } from "./pages/login.slint";
import { AppStatus, AppKeys } from "app-status.slint";
import { PlaylistProperty, Playlist } from "./pages/playlist.slint";
import { SongDetail, SongListProperty } from "./components/songlist.slint";
import { Player, PlayerProperty } from "components/player.slint";
import { VerticallDivider } from "components/divider.slint";
import { Route, RouteProperty } from "route.slint";
import { PlayQueueProperty } from "./pages/playqueue.slint";
import { Frame, FrameProperty } from "components/frame.slint";
import { LyricsPage, LyricsPageProperty } from "pages/lyrics_page.slint";
import { LyricsPropery, LyricsLine } from "components/lyrics.slint";

export {
    LoginProperty,
    AppStatus,
    SongDetail,
    PlaylistProperty,
    SongListProperty,
    PlayerProperty,
    SideBarProperty,
    SideBarItemMessage,
    RouteProperty,
    PlayQueueProperty,
    FrameProperty,
    LyricsPageProperty,
    LyricsPropery,
    LyricsLine
}

export component AppWindow inherits Window {
    default-font-family: "Microsoft YaHei UI";
    default-font-weight: 400;
    background: transparent;
    preferred-height: 1080px * 0.5;
    preferred-width: 1920px * 0.5;

    property <color> main-content-color: Palette.white.with-alpha(0.6);

    no-frame: true;
    resize-border-width: 6px;

    if AppStatus.logined : Rectangle {
        upper := Rectangle {
            horizontal-stretch: 1;
            height: root.height - player.height;
            y: 0;
            Rectangle {
                width: 100%;
                sidebar := SideBar {
                    x: 0;
                    background: Palette.neutral-lighter.with-alpha(0.3);
                    height: 100%;
                }

                VerticallDivider {
                    x: sidebar.current-width;
                    height: 100%;
                }

                Rectangle {
                    x: sidebar.current-width;
                    width: root.width - self.x;
                    title_bar := Frame {
                        y: 0;
                        background: root.main-content-color;
                        width: parent.width;
                        enable: !LyricsPageProperty.display;
                    }

                    main_content := Rectangle {
                        y: title_bar.height;
                        width: parent.width;
                        height: parent.height - self.y;

                        background: root.main-content-color;
                        out property <length>  max-width-t: 1280px;
                        out property <length>  min-width-t: 600px;

                        pure function calculate-margin() -> length {
                            if self.width > max-width-t {
                                return (self.width - max-width-t) / 2 + 60px;
                            }

                            return 60px;
                        }

                        Route {
                            margin: calculate-margin();
                        }
                    }
                    
                    animate x {
                        duration: 120ms;
                        easing: ease-out;
                    }
                }
            }
            visible: !LyricsPageProperty.display;
        }

        // if LyricsPageProperty.display : 
        LyricsPage {
            height: root.height - player.height;
            width: root.width;
            x: 0;
            y: 0;
        }
        

        player := Player {
            background: root.main-content-color;
            height: 111px;
            y: upper.height;
        }
    }

    
    if !AppStatus.logined: Login{ }
}
