export global AppStatus {
    in-out property <bool> logined: true;
    in-out property <int> login-id-1;
    in-out property <int> login-id-2;

    in-out property <bool> loading: false;
    in-out property <bool> show-playing: false;
}

export global AppKeys {
    in-out property <bool> control;
    in-out property <bool> shift;
    in-out property <bool> meta;
    in-out property <bool> alt;

    in-out property <string> key;
}


export global ScrollStatus {
    in-out property <length> viewport-height;
    in-out property <length> viewport-y;
}

