import { VerticalBox, ScrollView } from "std-widgets.slint";
import { Palette } from "palette.slint";
import { IconFont } from "./assets/icon/iconfont.slint";
import { HorizontalDivider, VerticallDivider } from "./components/divider.slint";

export struct SideBarItemMessage {
    cover: image,
    name: string,
    route: string
}

export global SideBarProperty {
    callback update();

    in-out property <[SideBarItemMessage]> created-playlist;
    in-out property <[SideBarItemMessage]> subscribed-playlist;
}


struct BarAnimationFrame {
    y: length,
    height: length,
    duration: duration,
    visible: bool
}

component SideBarItem inherits Rectangle {
    // 选中
    in-out property <int> active-item-id;
    in property <int> item-id;

    // 文字环图标
    in property <string> text;
    in property <string> iconfont;

    // 动画
    in-out property <bool> active : item-id == active-item-id;
    in-out property <int> animation-phase: 0;
    in-out property <int> move-direction; // 动画方向

    // 是否收起
    in-out property <bool> toggled: false;

    // 动画绑定
    changed active => {
        if (active) {
            blue_bar.animate-in = true;
        } else {
            blue_bar.animate-in = false;
        }
        blue_bar.animation-phase = 1;
    }

    // 静态属性
    height: 36px;
    border-radius: 4px;
    clip: true;

    
    // 小蓝条
    blue_bar :=  Rectangle{
        // 进入动画还是退出动画
        in-out property <bool> animate-in: false;
        in-out property <int> move-direction : parent.move-direction;
        
        // 计算初值
        private property <length> initial_y : (parent.height - self.initial_height) / 2;
        private property <length> initial_height: 18px;
        
        // 设置动画初始帧
        property <int> animation-phase <=> parent.animation-phase;

        // 定义关键帧
        property <[BarAnimationFrame]> animation-frame : [
            { // 完结后属性
                y: initial_y,
                height: initial_height,
                duration: 0ms,
                visible: active
            },
            { // 增大
                y: move-direction < 0 ? initial_y : initial_y - 10px,
                height: initial_height + 10px,
                duration: 200ms,
                visible: !animate-in
            },
            { // 跳出
                y: move-direction < 0 ? initial_y + 2 * initial_height : initial_y - 2 * initial_height,
                height: initial_height + 10px,
                duration: 25ms,
                visible: !animate-in
            },
            { // 跳入
                y: move-direction < 0 ? initial_y - 10px : initial_y,
                height: initial_height + 10px,
                duration: 25ms,
                visible: animate-in
            },
            { // 缩小
                y: initial_y,
                height: initial_height,
                duration: 200ms,
                visible: animate-in
            }
        ];

        // 动画时钟
        animation-tick := Timer{
            interval: animation-frame[animation-phase].duration;
            running: animation-phase != 0;
            triggered => {
                animation-phase = Math.mod(animation-phase + 1, animation-frame.length);
            }
        }

        // 动画声明
        animate y,height {
            duration: animation-frame[animation-phase].duration;
        }

        height: animation-frame[animation-phase].height;
        y: animation-frame[animation-phase].y;
        visible: animation-frame[animation-phase].visible;

        width: 3px;
        border-radius: 2px;
        x: 0px;
        background: Palette.theme-primary;
    }

    // 主要内容
    content :=HorizontalLayout {
        width: 100%;
        height: 100%;
        x: 0px;

        if !root.iconfont.is-empty: icon:= IconFont {
            text: root.iconfont;
            font-size: self.height - 18px;
            vertical-alignment: center;
            horizontal-alignment: center;
            height: 100%;
            width: 35px;
        }
        
        if !toggled: Text {
            text: text;
            vertical-alignment: center;
            font-size: 14px;
        }
    }
    
    // 状态
    states [
        clicked when active: {
            background: Palette.neutral-light;
        }

        hover when ta.has-hover && !active: {
            background: Palette.neutral-light;
        }
    ]

    ta := TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            move-direction = active-item-id - item-id;
            active-item-id = item-id;
        }
    }
}

export struct Item {
    text: string,
    iconfont: string,
}

export component SideBar inherits Rectangle {
    in-out property <[Item]> items : [
        {
            text: "主页",
            iconfont: "\u{e710}"
        }, {
            text: "喜欢的音乐",
            iconfont: "\u{e6fb}"
        }
    ];

    in-out property <int> active-item-id : 0;
    in-out property <bool> toggled: false;
    
    out property <length> initia-with: 300px;
    out property <length> compact-width: 35px + main_item.padding * 2;

    width: toggled ? compact-width : initia-with;
    clip: true;
    out property <length> current-width : toggled ? compact-width : initia-with;
    callback current-width-changed();

    init => {
        current-width-changed();
        SideBarProperty.update();
    }

    changed current-width => {
        current-width-changed()
    }

    Timer {
        interval: 4 * 60s;
        running: true;
        triggered => {
            SideBarProperty.update();
        }
    }

    property <int> move-direction;
    main_item := VerticalBox {
        width: 100%;
        spacing: 4px;
        
        toggle-button:= Rectangle {
            height: 36px;
            width: 35px;
            VerticalLayout {
                IconFont {
                    overflow: TextOverflow.clip;
                    text: "\u{f076a}";
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    height: 100%;
                    width: 35px;
                    font-size: 18px;
                    ta :=TouchArea {
                        clicked => {
                            toggled = !toggled;
                        }
                    }
                }
            }
            border-radius: 4px;
            states [
                hover when ta.has-hover: {
                    background: Palette.theme-lighter;
                }
            ]
        }

        ScrollView {
            vertical-stretch: 1;
            VerticalLayout {
                spacing: 4px;
                alignment: LayoutAlignment.stretch;
                for item[i] in items : SideBarItem {
                    item-id: i;
                    text: item.text;
                    iconfont: item.iconfont;
                    active-item-id <=> root.active-item-id;
                    move-direction <=> root.move-direction;
                    toggled: root.toggled;
                }
                HorizontalDivider {}
                for item[i] in SideBarProperty.created-playlist : SideBarItem{
                    item-id: i + 20;
                    text: item.name;

                    active-item-id <=> root.active-item-id;
                    move-direction <=> root.move-direction;
                    toggled: root.toggled;
                }
            }
        }
 
        setting-item := SideBarItem {
            item-id: 100000000;
            text: "设置";
            active-item-id <=> root.active-item-id;
            move-direction <=> root.move-direction;
            toggled: root.toggled;
            iconfont: "\u{ea94}";
        }
    }

    animate width {
        duration: 100ms;
        easing: ease-out;
        delay: 10ms;
    }

}
