import { VerticalBox, ScrollView, ListView } from "std-widgets.slint";
import { Palette } from "palette.slint";
import { IconFont } from "./assets/icon/iconfont.slint";
import { HorizontalDivider, VerticallDivider } from "./components/divider.slint";
import { RouteProperty } from "./route.slint";
import { MarginBox } from "components/margin-box.slint";

export struct SideBarItemMessage {
    name: string,
    route: string,
    grade: int,
    father: int,
    icon: image,
    iconfont: string,
    display: bool,
    expand: bool,
    type: int,
    index: int
}

export global SideBarProperty {
    callback update();
    callback expand(int);
    callback toggle(bool);
    
    in-out property <[SideBarItemMessage]> sidebar-items;
    in-out property <[SideBarItemMessage]> sidebar-items-show;

    in-out property <length> scroll-length;
}


struct BarAnimationFrame {
    y: length,
    height: length,
    duration: duration,
    visible: bool
}

component SideBarItem inherits Rectangle {
    in property <int> grade; 
    in property <bool> is-container;
    // 页面路径
    in property <string> page-path;

    // 选中
    in-out property <int> active-item-id;
    in property <int> item-id;

    // 文字和图标
    in property <string> text;
    in property <string> iconfont;
    in property <image> icon;

    // 动画
    in-out property <bool> active : item-id == active-item-id;
    in-out property <int> animation-phase: 0;
    in-out property <int> move-direction; // 动画方向

    // 是否收起
    in-out property <bool> toggled: false;

    // 动画绑定
    changed active => {
        if (active) {
            blue_bar.animate-in = true;
        } else {       
            blue_bar.animate-in = false;
        }
        blue_bar.animation-phase = 1;
    }

    // 静态属性
    height: 36px;
    border-radius: 4px;
    clip: true;

    ta := TouchArea {
        width: 100%;
        height: 100%;

        in-out property <bool> left-down: false;
        clicked => {
            if is-container && !toggled {
                SideBarProperty.expand(item-id);
            }

            if RouteProperty.navigate(root.page-path) {
                move-direction = active-item-id - item-id;
                active-item-id = item-id;
            }
        }

        pointer-event(event) => {
            if event.button == PointerEventButton.left {
                if event.kind == PointerEventKind.down {
                    left-down = true;
                } else {
                    left-down = false;
                }
            }
        }
    }

    Rectangle {
        x: grade * 36px;
        width: parent.width - self.x;
        // 小蓝条
        blue_bar :=  Rectangle{
            // 进入动画还是退出动画
            in-out property <bool> animate-in: false;
            in-out property <int> move-direction : root.move-direction;
            
            // 计算初值
            private property <length> initial_y : (parent.height - self.initial_height) / 2;
            private property <length> initial_height: 18px;
            
            // 设置动画初始帧
            property <int> animation-phase <=> root.animation-phase;

            // 定义关键帧
            property <[BarAnimationFrame]> animation-frame : [
                { // 完结后属性
                    y: initial_y,
                    height: initial_height,
                    duration: 0ms,
                    visible: active
                },
                { // 增大
                    y: move-direction < 0 ? initial_y : initial_y - 10px,
                    height: initial_height + 10px,
                    duration: 200ms,
                    visible: !animate-in
                },
                { // 跳出
                    y: move-direction < 0 ? initial_y + 2 * initial_height : initial_y - 2 * initial_height,
                    height: initial_height + 10px,
                    duration: 25ms,
                    visible: !animate-in
                },
                { // 跳入
                    y: move-direction < 0 ? initial_y - 10px : initial_y,
                    height: initial_height + 10px,
                    duration: 25ms,
                    visible: animate-in
                },
                { // 缩小
                    y: initial_y,
                    height: initial_height,
                    duration: 200ms,
                    visible: animate-in
                }
            ];

            // 动画时钟
            animation-tick := Timer{
                interval: animation-frame[animation-phase].duration;
                running: animation-phase != 0;
                triggered => {
                    animation-phase = Math.mod(animation-phase + 1, animation-frame.length);
                }
            }

            // 动画声明
            animate y,height {
                duration: animation-frame[animation-phase].duration;
            }

            height: animation-frame[animation-phase].height;
            y: animation-frame[animation-phase].y;
            visible: animation-frame[animation-phase].visible;

            width: 3px;
            border-radius: 2px;
            x: 0px;
            background: Palette.theme-primary;
        }


        // 主要内容
        content :=HorizontalLayout {
            width: 100%;
            height: 100%;
            spacing: 10px;
            x: 6px;

            if !root.iconfont.is-empty : IconFont {
                text: root.iconfont;
                font-size: 20px;
                vertical-alignment: center;
                horizontal-alignment: center;
                height: 100%;
                width: 24px;
            }

            if root.iconfont.is-empty : Rectangle {
                width: 24px;
                Rectangle {
                    height: 22px;
                    width: 22px;
                    clip: true;
                    border-radius: 4px;
                    Image {
                        source: icon;
                        height: 100%;
                        width: 100%;
                    }
                }
            }

            HorizontalLayout {
                alignment: start;
                if !toggled: Text {
                    text: text;
                    vertical-alignment: center;
                    font-size: 14px;
                    overflow: elide;
                }

                horizontal-stretch: 1;
            }
            
            if is-container : Rectangle {
                // down f0320
                // up f0323
            }
        }
    }
    
    
    // 状态
    states [
        left-down when ta.left-down : {
            background: Palette.neutral-light.with-alpha(0.85);
        }
        clicked when active: {
            background: Palette.neutral-light.with-alpha(0.70);
        }

        hover when ta.has-hover && !active: {
            background: Palette.neutral-light.with-alpha(0.70);
        }
    ]
}

component ToggleButton inherits Rectangle{
    in-out property <bool> toggled;
    IconFont {
        overflow: TextOverflow.clip;
        text: "\u{f076a}";
        horizontal-alignment: center;
        vertical-alignment: center;
        height: 100%;
        width: 24px;
        font-size: 18px;
        ta := TouchArea {
            in-out property <bool> left-down: false;
            clicked => {
                root.toggled = !root.toggled;
                SideBarProperty.toggle(root.toggled);
            }

            pointer-event(event) => {
                if event.button == PointerEventButton.left {
                    if event.kind == PointerEventKind.down {
                        left-down = true;
                    } else {
                        left-down = false;
                    }
                }
            }
        }
    }

    border-radius: 4px;

    states [
        left-down when ta.left-down : {
            background: Palette.neutral-light.with-alpha(0.85);
        }
        hover when ta.has-hover: {
            background: Palette.neutral-light.with-alpha(0.70);
        }
    ]
}

export component SideBar inherits Rectangle {
    in-out property <int> active-item-id : 0;
    in-out property <bool> toggled : false;
    
    out property <length> initia-with: 300px;
    out property <length> compact-width: 44px;

    width: toggled ? compact-width : initia-with;
    clip: true;
    out property <length> current-width : toggled ? compact-width : initia-with;
    callback current-width-changed();

    init => {
        current-width-changed();
        SideBarProperty.update();
    }

    changed current-width => {
        current-width-changed()
    }

    Timer {
        interval: 4 * 60s;
        running: true;
        triggered => {
            // SideBarProperty.update();
        }
    }

    property <int> move-direction;

    // enum SideBarItemType {
    //     Common = 0,
    //     Container = 1,
    //     Divider = 2,
    // }

    property <int> common: 0;
    property <int> container: 1;
    property <int> divider: 2;

    VerticalLayout {
        padding-left: 4px;
        // padding-right: 4px;
        toggle-button:= Rectangle {
            height: 36px;
            width: 36px;
            ToggleButton {
                width: 100%;
                toggled <=> root.toggled;
            }
        }

        list := ListView {
            horizontal-stretch: 1;
            width: 100%;
            for item[i] in SideBarProperty.sidebar-items-show : Rectangle {
                x: 0;
                width: parent.width - 4px;
                height: item.type == divider ? 1px : 40px;
                clip: item.display;
                if item.type == divider : HorizontalDivider {}

                content := HorizontalLayout {
                    y: 0px;
                    padding-top: 2px;
                    padding-bottom: 2px;
                    if item.type == common : SideBarItem {
                        item-id: item.index;
                        text: item.name;
                        iconfont: item.iconfont;
                        icon: item.icon;
                        page-path: item.route;
                        grade: item.grade;
                        active-item-id <=> root.active-item-id;
                        move-direction <=> root.move-direction;
                        toggled: root.toggled;
                    }

                    if item.type == container : SideBarItem {
                        item-id: item.index;
                        text: item.name;
                        iconfont: item.iconfont;
                        icon: item.icon;
                        grade: item.grade;
                        active-item-id <=> root.active-item-id;
                        move-direction <=> root.move-direction;
                        is-container: true;
                        toggled: root.toggled;
                    }
                }
            }

        }

        VerticalLayout {
            padding-right: 4px;
            HorizontalDivider {
                visible: list.height < list.viewport-height;
            }
            setting-item := SideBarItem {
                item-id: 100000000;
                text: "设置";
                iconfont: "\u{ea94}";
                active-item-id <=> root.active-item-id;
                move-direction <=> root.move-direction;
                toggled: root.toggled;
            }
        }
    }

    animate width {
        duration: 100ms;
        easing: ease-out;
        delay: 10ms;
    }
}
